services:

  postgres:

    image: postgis/postgis:17-3.5

    container_name: oiip-postgres

    environment:
      POSTGRES_DB: oiip
      POSTGRES_USER: oiip
      POSTGRES_PASSWORD: oiip

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:

    build: .

    container_name: oiip-api

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    env_file:
      - .env

volumes:

  postgres_data: