"""add index to country_code in site model

Revision ID: 781ee002b5cd
Revises: b3ba8de944d4
Create Date: 2026-06-05 20:27:18.312576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '781ee002b5cd'
down_revision: Union[str, Sequence[str], None] = 'b3ba8de944d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_site_country_code'), 'site', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_country_code'), table_name='site')
    # ### end Alembic commands ###
