"""extend site model with status and constraints

Revision ID: b3ba8de944d4
Revises: 1edb5a9cb6ea
Create Date: 2026-06-05 19:52:37.392674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ba8de944d4'
down_revision: Union[str, Sequence[str], None] = '1edb5a9cb6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Определяем объект Enum для управления типом в БД
enum_name = 'sitestatus'
status_enum = sa.Enum('CANDIDATE', 'RESEARCH', 'VALIDATED', 'REJECTED', 'SELECTED', name=enum_name)


def upgrade() -> None:
    """Upgrade schema."""
    # СНАЧАЛА явно создаем тип ENUM в PostgreSQL
    status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('description', sa.String(length=1000), nullable=True, comment='OTEC candidate. Near deep-water coast. Fiber landing nearby.'))
    op.add_column('site', sa.Column('status', status_enum, server_default='CANDIDATE', nullable=False, comment='Lifecycle status: candidate, research, validated, rejected, selected'))
    op.add_column('site', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('site', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###

    # Ограничение длины country_code на уровне СУБД
    op.create_check_constraint(
        'check_country_code_length',
        'site',
        'length(country_code) = 2'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Удаляем ограничение
    op.drop_constraint('check_country_code_length', 'site', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'updated_at')
    op.drop_column('site', 'created_at')
    op.drop_column('site', 'status')
    op.drop_column('site', 'description')
    # ### end Alembic commands ###
    
    # Удаляем тип ENUM из базы данных при откате, чтобы не оставлять мусор
    status_enum.drop(op.get_bind(), checkfirst=True)